<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Definitions" data-toc-modified-id="Definitions-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Definitions</a></span><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Row-Equivalent-Matrices" data-toc-modified-id="Row-Equivalent-Matrices-1.0.0.1"><span class="toc-item-num">1.0.0.1&nbsp;&nbsp;</span>Row Equivalent Matrices</a></span></li><li><span><a href="#Echelon-Matrix-(row-echelon-form)" data-toc-modified-id="Echelon-Matrix-(row-echelon-form)-1.0.0.2"><span class="toc-item-num">1.0.0.2&nbsp;&nbsp;</span>Echelon Matrix (row echelon form)</a></span></li><li><span><a href="#Reduced-Echelon-Matrix-(reduced-row-echelon-form)" data-toc-modified-id="Reduced-Echelon-Matrix-(reduced-row-echelon-form)-1.0.0.3"><span class="toc-item-num">1.0.0.3&nbsp;&nbsp;</span>Reduced Echelon Matrix (reduced row echelon form)</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Theorems" data-toc-modified-id="Theorems-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Theorems</a></span><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Equivalent-Systems-and-Equivalent-Matrices" data-toc-modified-id="Equivalent-Systems-and-Equivalent-Matrices-2.0.0.1"><span class="toc-item-num">2.0.0.1&nbsp;&nbsp;</span>Equivalent Systems and Equivalent Matrices</a></span></li><li><span><a href="#Theorem-1:-Unique-Reduced-Echelon-Form" data-toc-modified-id="Theorem-1:-Unique-Reduced-Echelon-Form-2.0.0.2"><span class="toc-item-num">2.0.0.2&nbsp;&nbsp;</span>Theorem 1: Unique Reduced Echelon Form</a></span></li><li><span><a href="#Theroem-2:-The-Three-Possibilities" data-toc-modified-id="Theroem-2:-The-Three-Possibilities-2.0.0.3"><span class="toc-item-num">2.0.0.3&nbsp;&nbsp;</span>Theroem 2: The Three Possibilities</a></span></li><li><span><a href="#Theorem-3:-Homogenous-Systems-with-More-Variables-than-Equations" data-toc-modified-id="Theorem-3:-Homogenous-Systems-with-More-Variables-than-Equations-2.0.0.4"><span class="toc-item-num">2.0.0.4&nbsp;&nbsp;</span>Theorem 3: Homogenous Systems with More Variables than Equations</a></span></li><li><span><a href="#Theorem-4:-Homogenous-Systems-with-Unique-Solutions" data-toc-modified-id="Theorem-4:-Homogenous-Systems-with-Unique-Solutions-2.0.0.5"><span class="toc-item-num">2.0.0.5&nbsp;&nbsp;</span>Theorem 4: Homogenous Systems with Unique Solutions</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Algorithms" data-toc-modified-id="Algorithms-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Algorithms</a></span><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Back-Substitution" data-toc-modified-id="Back-Substitution-3.0.0.1"><span class="toc-item-num">3.0.0.1&nbsp;&nbsp;</span>Back Substitution</a></span></li><li><span><a href="#Gaussian-Elimination" data-toc-modified-id="Gaussian-Elimination-3.0.0.2"><span class="toc-item-num">3.0.0.2&nbsp;&nbsp;</span>Gaussian Elimination</a></span></li><li><span><a href="#Gauss-Jordan-Elimination" data-toc-modified-id="Gauss-Jordan-Elimination-3.0.0.3"><span class="toc-item-num">3.0.0.3&nbsp;&nbsp;</span>Gauss-Jordan Elimination</a></span></li></ul></li></ul></li></ul></li></ul></div>

## Definitions

##### Row Equivalent Matrices
* Two matrices are equivalent if one can be obtained by the other by a finite sequence of row operations

##### Echelon Matrix (row echelon form)
The matrix R is called an echelon matrix provided it has the following properties,
* **Prop. 1)** Every row of R that consists entirely of zeros (if any) lies beneath every row that contains a nonzero element
* **Prop. 2)** In each row of R that contains a nonzero element, the first element is strictly to the right  of the first nonzero element of the preceeding row (if any) 
* **Prop. 3)** All entries below a pivot are zero

##### Reduced Echelon Matrix (reduced row echelon form)
A **reduced echelon matrix R** is an echelon matrix that has -- in addition to Properties 1 & 2 -- the following properties:
* **Prop. 3)** Each leading entry of R is 1
* **Prop. 4)** Each leading entry of R is the only nonzero element in its column

## Theorems

##### Equivalent Systems and Equivalent Matrices
* If the augmented coefficient matrices of two linear systems are row equivalent, the two systems have the same solution set

##### Theorem 1: Unique Reduced Echelon Form
* Every matrix is row equivalent to one and only one reduced echelon matrix

##### Theroem 2: The Three Possibilities
A linear system of equations has either
* A unique solution
* No solution
* Infinite solutions

##### Theorem 3: Homogenous Systems with More Variables than Equations
* Every homogenous linear system with more variables than equations has infinitely many solutions. 

##### Theorem 4: Homogenous Systems with Unique Solutions
* Let R be an `n x n` matrix. Then the homogenous system with coefficient matrix R has only the trivial solution if and only if R is row equivalent to the `n x n` identity matrix
    

## Algorithms

##### Back Substitution
* **Step #1)** Set each free variable equal to an arbitraryparamenter (a diferent parameter for each free variable)
* **Step #2)** Solve the final (nonzero) equation for its leading variable
* **Step #3)** Substitute the result in the next-to-last equation and then solve for its leading variable
* **Step #4)** Continuing in this fashion, work upward through the system of equations until all variabnles have been determined

##### Gaussian Elimination
* **Step #1)** Locate the first column of R that contains a nonzero element
* **Step #2)** If the first (top) entry in this column is zero, interchange the first row of R with a row in which the corresponding entry is zero
* **Step #3)** Now that the first entry is nonzero. replace the entries below it in the same column with zeros by adding appropriate multiples of the fist row of R to lower rows
* **Step #4)** There may be several initial columns of zeros or none at all, Perform steps 1 - 3 on the subsequent columns. 
* **Step #5)** Repeat this cycle untill an echelon matrix is obtained

##### Gauss-Jordan Elimination
* **Step #1)** First transform R into echelon form by Gaussian elimination
* **Step #2)** Divide each element of each nonzero row by its leading entry (to satisfy property 3)
* **Step #3)** Finally, use each leading 1 to "clear out" any remaining nonzero elements in its colummn (to satisfy property 4)

In [1]:
import numpy as np
from numpy import linalg 
import sympy
from matplotlib import pyplot as plt

###### Defining the matrix with row 1 and row 2 switched and also, switching row 2 and row 3

In [2]:
R = np.matrix([[1,3,5,-2],[3,7,7,6],[0,1,4,-5]])
R

matrix([[ 1,  3,  5, -2],
        [ 3,  7,  7,  6],
        [ 0,  1,  4, -5]])

###### Renaming rows
* When performing row operations, Note that the row being changed needs to be referenced by row index

###### Referencing rows with a numpy matrix
* Rows are referenced like arrays, using a `[]` and index number.
* Remember that in an array, the 1st index number is zero, so zero is referencing row #1
* So, the 3rd row of the `r` matrix is `r[2]`
* The colon `:`is a slicing operator, everything to the right of it is sliced from the row
* So by calling `r[2,:]` you are getting all of row 3
* You don't have to use the colon if referencing the entire row but it is an example of how to slice it
* Note that this is very similar to Matlab which uses parenthesis `r(3,:)`
* If it's easier, just assign the rows a new variable for quick manipulation

In [3]:
R1 = R[0]
R2 = R[1]
R3 = R[2]

In [4]:
R

matrix([[ 1,  3,  5, -2],
        [ 3,  7,  7,  6],
        [ 0,  1,  4, -5]])

###### Recall the 3 types of row operatoins
* 1) Multiply any single row of R by a nonzero constant `cRp`
* 2) Interchange two rows of R `swap(Rp,Rq)`
* 3) Add a constant multiple of one row of R to another row `(c)*Rp + Rq`

###### Remember there are 3 possibilities for the solution to a system of linear equations
* There is exactly one unique solution (geometrically the lines on their respective graphs intersect)
* There is no solution (The lines are parallel and therefore continue infinitely without ever intersecting)
* There are infinite solutions (the lines coincide and are equal at all points to infinity)

###### Basic row operations
* 1st we will multiply row 3 by -3 and add it to row 2 to get the new row 2

In [5]:
# Remember that the row being changed is referenced by row index, not by the new variable we assigned R[1] = row 2
R[1] = -3*R1 + R2

In [6]:
# here is our new matrix
R

matrix([[ 1,  3,  5, -2],
        [ 0, -2, -8, 12],
        [ 0,  1,  4, -5]])